version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map host port 3000 to container port 80
    volumes:
      - .:/app # Mount the current directory into the container for development
    environment:
      - NODE_ENV=development

  # Optional: Add a separate production service if needed
  # prod:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:80"
  #   environment:
  #     - NODE_ENV=production
