version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3010:3010" # Map host port 3010 to container port 3010
    volumes:
      - .:/app # Mount the current directory to the container
      - /app/node_modules # Prevents overwriting node_modules with local files
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true  # Enable polling for file changes
