version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "80:80" # Map host port 80 to container port 80 for Nginx
    environment:
      - NODE_ENV=production
